# For more information see: https://black.readthedocs.io/en/stable/integrations/github_actions.html
name: Lint

on: 
  # Allows you to run this workflow from another workflow
  workflow_call

# disable all the permission for the workflow
permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      
      # Codespell check
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install codespell
        run: pip install codespell
      - name: Run codespell with pyproject.toml config
        run: codespell -w --toml pyproject.toml
      
      # Commit and push codespell fixes
      - name: Commit codespell fixes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          if git diff --staged --quiet; then
            echo "No codespell changes to commit"
          else
            git commit -m "Fix spelling errors with codespell"
            git push
          fi

      # Black formatting check
      - uses: psf/black@stable
        with:
          jupyter: true
      
